Agent basic stats
agh-docker-monitoring/dockiera-agent pull request #2
Opened 2021-06-08 10:14 UTC by Ilargi12

2021-06-13 20:05 UTC, kraleppa approved these changes

2021-06-13 20:27 UTC, jakubsolecki requested changes
Comment your code, please

2021-06-13 20:27 UTC, jakubsolecki commented on agent.py
>              print(f"Configuration failed due to : {e}")
Would be nice to mark it as an error (eg. [ERROR] label at the beginning of string)
```suggestion
            print(f"[ERROR] Configuration failed due to : {e}")
```

2021-06-22 20:08 UTC, jakubsolecki approved these changes

2021-06-22 20:27 UTC, merged